# Generated by Django 5.2.7 on 2025-10-27 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_initial'),
        ('log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='viewlog',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='viewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user'], name='log_searchh_user_id_e6aa44_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['location'], name='log_searchh_locatio_64d680_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['created_at'], name='log_searchh_created_3a929b_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['user', 'listing'], name='log_viewlog_user_id_3552b6_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['listing'], name='log_viewlog_listing_b9d0d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viewlog',
            unique_together={('user', 'listing', 'viewed_at')},
        ),
    ]
