# Generated by Django 5.2.7 on 2025-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
