version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME:-rental_hub}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
    restart: always
    env_file:
      - ../backend/${ENV_FILE:-.env.dev}
    depends_on:
      - db
      - redis
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
      "

  celery:
    build:
      context: ../backend
    restart: always
    env_file:
      - ../backend/${ENV_FILE:-.env.dev}
    depends_on:
      - redis
      - backend
    command: celery -A myproject worker -l info

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../backend/staticfiles:/static
      - ../backend/media:/media
    depends_on:
      - backend

volumes:
  mysql_data:
