# Generated by Django 5.2.7 on 2025-10-27 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user'], name='feedbacks_f_user_id_9e12bc_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['listing'], name='feedbacks_f_listing_da6aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='feedbacks_f_rating_710d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'listing')},
        ),
    ]
